"""
api.py — PeerGlass REST API
============================
A thin FastAPI wrapper around the same rir_client.py logic that powers
the MCP server. This makes every tool available as a plain HTTP endpoint,
compatible with any LLM (OpenAI function calling, Gemini tool use, etc.),
any HTTP client, or any browser.

Architecture:
                ┌─────────────────────────────────────┐
                │         Your Code / LLM              │
                │  (Claude, OpenAI, Gemini, curl, ...)  │
                └──────────────┬──────────────────────┘
                               │  HTTP REST
                               ▼
                ┌─────────────────────────────────────┐
                │         api.py  (FastAPI)             │
                │   /v1/ip   /v1/asn   /v1/health ...  │
                └──────────────┬──────────────────────┘
                               │  Python call (same code)
                               ▼
                ┌─────────────────────────────────────┐
                │      rir_client.py  (shared logic)    │
                │  RDAP · RPKI · BGP · PeeringDB · ...  │
                └─────────────────────────────────────┘

Running locally:
    uvicorn api:app --host 0.0.0.0 --port 8000 --reload

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs       ← Swagger UI
    http://localhost:8000/redoc      ← ReDoc

All endpoints accept ?format=markdown (default) or ?format=json
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from fastapi import FastAPI, Query, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, PlainTextResponse
from pydantic import BaseModel
from typing import Optional
import asyncio

import rir_client
import cache as cache_module
from formatters import (
    format_ip_results_md,
    format_asn_results_md,
    format_abuse_contact_md,
    format_rpki_result_md,
    format_bgp_status_md,
    format_org_audit_md,
    format_prefix_history_md,
    format_transfer_detect_md,
    format_ipv4_stats_md,
    format_prefix_overview_md,
    format_peering_info_md,
    format_ixp_lookup_md,
    format_network_health_md,
    format_change_monitor_md,
    to_json,
)
from normalizer import normalize_ip_response, normalize_asn_response
from models import (
    RIRQueryResult, AbuseContact, OrgAuditResult,
    ResponseFormat,
)

# ──────────────────────────────────────────────────────────────
# App setup
# ──────────────────────────────────────────────────────────────

app = FastAPI(
    title="PeerGlass API",
    description=(
        "Universal REST API for internet resource intelligence. "
        "Query all 5 RIRs (AFRINIC, APNIC, ARIN, LACNIC, RIPE), "
        "validate RPKI routes, check BGP status, look up PeeringDB, "
        "trace allocation history, and monitor resources for changes.\n\n"
        "Compatible with any HTTP client, LLM function-calling interface "
        "(OpenAI, Gemini, Claude), or browser.\n\n"
        "Source: https://github.com/peerglass/peerglass  "
        "| License: MIT"
    ),
    version="1.0.0",
    contact={
        "name": "PeerGlass",
        "url": "https://peerglass.io",
    },
    license_info={
        "name": "MIT",
        "url": "https://opensource.org/licenses/MIT",
    },
)

# Allow all origins for public demo use
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ──────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────

FORMAT_QUERY = Query(
    default="markdown",
    description="Response format: 'markdown' for human-readable, 'json' for machine-readable",
    pattern="^(markdown|json)$",
)

def _resp(md: str, jsn: str, fmt: str):
    """Return markdown as plain text or json as JSON based on format param."""
    if fmt == "json":
        import json
        try:
            return JSONResponse(content=json.loads(jsn))
        except Exception:
            return JSONResponse(content={"raw": jsn})
    return PlainTextResponse(content=md, media_type="text/markdown")


# ──────────────────────────────────────────────────────────────
# Root + Health
# ──────────────────────────────────────────────────────────────

@app.get("/", tags=["Meta"], summary="API root — links to docs")
async def root():
    return {
        "name": "PeerGlass API",
        "version": "1.0.0",
        "description": "Internet resource intelligence: RIR + BGP + RPKI + PeeringDB",
        "docs": "/docs",
        "redoc": "/redoc",
        "tools": 17,
        "endpoints": {
            "ip":           "/v1/ip/{ip}",
            "asn":          "/v1/asn/{asn}",
            "abuse":        "/v1/abuse/{ip}",
            "rpki":         "/v1/rpki?prefix=...&asn=...",
            "bgp":          "/v1/bgp/{resource}",
            "announced":    "/v1/announced/{asn}",
            "org":          "/v1/org?name=...",
            "history":      "/v1/history/{resource}",
            "transfers":    "/v1/transfers/{resource}",
            "ipv4stats":    "/v1/stats/ipv4",
            "overview":     "/v1/overview/{prefix}",
            "peering":      "/v1/peering/{asn}",
            "ixp":          "/v1/ixp?query=...",
            "health":       "/v1/health/{resource}",
            "monitor":      "/v1/monitor/{resource}",
            "cache_stats":  "/v1/meta/cache",
            "server_status":"/v1/meta/status",
        },
    }


@app.get("/v1/meta/cache", tags=["Meta"], summary="Cache statistics")
async def meta_cache():
    """Returns the current in-memory cache health: total entries, alive, expired."""
    return cache_module.stats()


@app.get("/v1/meta/status", tags=["Meta"], summary="RIR server reachability")
async def meta_status():
    """Pings all 5 RIR RDAP servers and returns their status."""
    statuses = await rir_client.check_all_rir_status()
    return [s.model_dump() for s in statuses]


# ──────────────────────────────────────────────────────────────
# Phase 1 — RDAP Lookups
# ──────────────────────────────────────────────────────────────

@app.get(
    "/v1/ip/{ip}",
    tags=["RDAP"],
    summary="Who owns this IP address?",
    response_description="Registration info from the authoritative RIR",
)
async def query_ip(
    ip: str,
    format: str = FORMAT_QUERY,
):
    """
    Query all 5 RIRs and return the authoritative RDAP registration
    for an IPv4 or IPv6 address.

    Returns: holder, org, RIR, country, allocation dates, abuse contact.

    **Examples:** `1.1.1.1`, `8.8.8.8`, `2001:4860:4860::8888`
    """
    cache_key = cache_module.make_ip_key(ip)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    results = await rir_client.query_ip_all_rirs(ip)
    resources = [normalize_ip_response(r) for r in results if r.status == "ok"]

    if not resources:
        raise HTTPException(status_code=404, detail=f"No RDAP record found for {ip}")

    query_result = RIRQueryResult(query=ip, query_type="ip", results=resources)
    md  = format_ip_results_md(query_result)
    jsn = to_json(query_result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_IP)
    return _resp(md, jsn, format)


@app.get(
    "/v1/asn/{asn}",
    tags=["RDAP"],
    summary="Who owns this Autonomous System Number?",
)
async def query_asn(
    asn: str,
    format: str = FORMAT_QUERY,
):
    """
    Query all 5 RIRs for the RDAP registration of an ASN.

    Returns: org name, RIR, country, allocation date, contact info.

    **Examples:** `AS13335`, `AS15169`, `13335`
    """
    cache_key = cache_module.make_asn_key(asn)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    results = await rir_client.query_asn_all_rirs(asn)
    resources = [normalize_asn_response(r) for r in results if r.status == "ok"]

    if not resources:
        raise HTTPException(status_code=404, detail=f"No RDAP record found for {asn}")

    query_result = RIRQueryResult(query=asn, query_type="asn", results=resources)
    md  = format_asn_results_md(query_result)
    jsn = to_json(query_result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_ASN)
    return _resp(md, jsn, format)


@app.get(
    "/v1/abuse/{ip}",
    tags=["RDAP"],
    summary="Who do I report abuse to for this IP?",
)
async def get_abuse_contact(
    ip: str,
    format: str = FORMAT_QUERY,
):
    """
    Find the abuse contact email for an IP address.
    Use this to report spam, DDoS, or other abuse from that IP.

    **Examples:** `185.220.101.45`, `1.1.1.1`
    """
    cache_key = cache_module.make_abuse_key(ip)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    contact = await rir_client.get_abuse_contact(ip)
    md  = format_abuse_contact_md(contact)
    jsn = to_json(contact)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_ABUSE)
    return _resp(md, jsn, format)


# ──────────────────────────────────────────────────────────────
# Phase 2 — RPKI + BGP
# ──────────────────────────────────────────────────────────────

@app.get(
    "/v1/rpki",
    tags=["Routing Security"],
    summary="Is this BGP route RPKI valid?",
)
async def check_rpki(
    prefix: str = Query(..., description="IP prefix in CIDR notation, e.g. '1.1.1.0/24'"),
    asn: str    = Query(..., description="Origin ASN, e.g. 'AS13335' or '13335'"),
    format: str = FORMAT_QUERY,
):
    """
    Validate a BGP route using RPKI (Resource Public Key Infrastructure).

    RPKI uses cryptographic certificates (ROAs) to prove which ASN is
    authorized to announce a given prefix. An **invalid** result means
    the announcement is NOT authorized — potential BGP hijack.

    Results: `valid` | `invalid` | `not-found` | `unknown`
    """
    asn_num = asn.upper().lstrip("AS")
    cache_key = cache_module.make_rpki_key(prefix, asn_num)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.check_rpki(prefix, asn_num)
    md  = format_rpki_result_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_RPKI)
    return _resp(md, jsn, format)


@app.get(
    "/v1/bgp/{resource}",
    tags=["Routing Security"],
    summary="Is this prefix/ASN visible in global BGP?",
)
async def check_bgp(
    resource: str,
    format: str = FORMAT_QUERY,
):
    """
    Check if a prefix or ASN is currently announced in the global BGP routing table.

    Returns: announcement status, originating ASN(s), visibility percentage
    (% of BGP route collectors that see this route).

    **Examples:** `1.1.1.0/24`, `AS13335`, `8.8.8.0/24`
    """
    cache_key = cache_module.make_bgp_key(resource)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.get_bgp_status(resource)
    md  = format_bgp_status_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_BGP)
    return _resp(md, jsn, format)


@app.get(
    "/v1/announced/{asn}",
    tags=["Routing Security"],
    summary="What prefixes is this ASN announcing?",
)
async def get_announced(
    asn: str,
    format: str = FORMAT_QUERY,
):
    """
    List all IP prefixes currently announced by an ASN in the global BGP table.

    **Examples:** `AS13335`, `AS15169`
    """
    asn_num = asn.upper().lstrip("AS")
    cache_key = cache_module.make_bgp_key(f"announced-{asn_num}")
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.get_announced_prefixes(asn_num)
    from formatters import format_announced_prefixes_md
    md  = format_announced_prefixes_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_BGP)
    return _resp(md, jsn, format)


@app.get(
    "/v1/org",
    tags=["RDAP"],
    summary="Find all internet resources for an organization",
)
async def audit_org(
    name: str = Query(..., description="Organization name or handle, e.g. 'Cloudflare' or 'GOOGL-ARIN'"),
    format: str = FORMAT_QUERY,
):
    """
    Search all 5 RIRs for every IP block and ASN registered to an organization.

    Useful for M&A due diligence, security research, or footprint mapping.

    **Examples:** `Cloudflare`, `GOOGL-ARIN`, `Amazon`
    """
    cache_key = cache_module.make_org_key(name)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    resources, errors = await rir_client.search_org_all_rirs(name)
    ip_blocks = [r for r in resources if r.resource_type in ("ip", "entity")]
    asns      = [r for r in resources if r.resource_type == "asn"]
    audit = OrgAuditResult(
        org_query       = name,
        total_resources = len(resources),
        ip_blocks       = ip_blocks,
        asns            = asns,
        rirs_found_in   = list({r.rir for r in resources}),
        errors          = errors,
    )
    md  = format_org_audit_md(audit)
    jsn = to_json(audit)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_ORG)
    return _resp(md, jsn, format)


# ──────────────────────────────────────────────────────────────
# Phase 3 — History + Stats
# ──────────────────────────────────────────────────────────────

@app.get(
    "/v1/history/{resource}",
    tags=["History"],
    summary="Full registration history for a prefix or ASN",
)
async def prefix_history(
    resource: str,
    format: str = FORMAT_QUERY,
):
    """
    Chronological timeline of every ownership and status change ever recorded
    for an IP prefix or ASN. Best coverage for RIPE NCC resources.

    **Examples:** `8.8.8.0/24`, `AS15169`, `1.1.1.0/24`
    """
    cache_key = cache_module.make_history_key(resource)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.get_prefix_history(resource)
    md  = format_prefix_history_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_HISTORY)
    return _resp(md, jsn, format)


@app.get(
    "/v1/transfers/{resource}",
    tags=["History"],
    summary="Detect cross-org or cross-RIR resource transfers",
)
async def detect_transfers(
    resource: str,
    format: str = FORMAT_QUERY,
):
    """
    Detect past ownership or cross-RIR transfers for an IP prefix or ASN.
    Transfer types: org change 🏢, inter-RIR 🌍→🌎, intra-RIR 🔄

    **Examples:** `8.8.8.0/24`, `AS15169`
    """
    cache_key = cache_module.make_transfer_key(resource)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.detect_transfers(resource)
    md  = format_transfer_detect_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_TRANSFER)
    return _resp(md, jsn, format)


@app.get(
    "/v1/stats/ipv4",
    tags=["Statistics"],
    summary="Global IPv4 / IPv6 / ASN exhaustion dashboard",
)
async def ipv4_stats(
    rir: Optional[str] = Query(
        default=None,
        description="Filter to one RIR: AFRINIC, APNIC, ARIN, LACNIC, or RIPE. Leave empty for all 5.",
    ),
    include_blocks: bool = Query(
        default=False,
        description="Include raw delegated IPv4 block rows. Requires rir to be set.",
    ),
    status: Optional[str] = Query(
        default=None,
        description="Optional status filter for block rows: allocated, assigned, available (free is normalized).",
    ),
    country: Optional[str] = Query(
        default=None,
        description="Optional 2-letter country filter for block rows (e.g. GH, ZA).",
    ),
    limit: int = Query(
        default=100,
        ge=1,
        le=5000,
        description="Maximum block rows to return when include_blocks=true.",
    ),
    offset: int = Query(
        default=0,
        ge=0,
        le=1_000_000,
        description="Pagination offset for block rows when include_blocks=true.",
    ),
    format: str = FORMAT_QUERY,
):
    """
    Real-time global IPv4, IPv6, and ASN allocation statistics from all 5 RIRs.
    Sourced from NRO Extended Delegation Stats files (published daily).

    Use this to track IPv4 exhaustion, IPv6 adoption, and ASN growth.
    """
    rir_filter = (rir or "").upper().strip() or "all"
    cache_key  = cache_module.make_ipv4stat_key(
        rir_filter=rir_filter,
        include_blocks=include_blocks,
        status_filter=status,
        country_filter=country,
        limit=limit,
        offset=offset,
    )
    cached     = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.get_global_ipv4_stats(
        rir_filter=rir or None,
        include_blocks=include_blocks,
        status_filter=status,
        country_filter=country,
        limit=limit,
        offset=offset,
    )
    md  = format_ipv4_stats_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_IPV4STAT)
    return _resp(md, jsn, format)


@app.get(
    "/v1/overview/{prefix}",
    tags=["History"],
    summary="Prefix hierarchy: parent blocks, children, and BGP status",
)
async def prefix_overview(
    prefix: str,
    format: str = FORMAT_QUERY,
):
    """
    Rich hierarchical view of an IP prefix: who owns it, parent blocks
    (less-specifics), child assignments (more-specifics), and BGP status.

    **Examples:** `1.1.1.0/24`, `8.8.8.0/24`
    """
    cache_key = cache_module.make_overview_key(prefix)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.get_prefix_overview(prefix)
    md  = format_prefix_overview_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_OVERVIEW)
    return _resp(md, jsn, format)


# ──────────────────────────────────────────────────────────────
# Phase 4 — PeeringDB + Health + Monitor
# ──────────────────────────────────────────────────────────────

@app.get(
    "/v1/peering/{asn}",
    tags=["PeeringDB"],
    summary="PeeringDB: peering policy, IXP presence, NOC contacts",
)
async def peering_info(
    asn: str,
    format: str = FORMAT_QUERY,
):
    """
    Fetch peering policy, IXP presence, NOC/abuse contacts, and BGP
    neighbours for an ASN from PeeringDB + RIPE Stat.

    **Examples:** `AS13335`, `AS15169`, `AS1299`
    """
    asn_num = asn.upper().lstrip("AS")
    cache_key = cache_module.make_peering_key(asn_num)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.get_peering_info(asn_num)
    md  = format_peering_info_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_PEERING)
    return _resp(md, jsn, format)


@app.get(
    "/v1/ixp",
    tags=["PeeringDB"],
    summary="Find Internet Exchange Points by country or name",
)
async def ixp_lookup(
    query: str = Query(..., description="2-letter country code (e.g. 'MU') or IXP name fragment (e.g. 'AMS-IX')"),
    format: str = FORMAT_QUERY,
):
    """
    Search PeeringDB for Internet Exchange Points by country code or name.

    **Examples:** `MU` (Mauritius), `ZA` (South Africa), `AMS-IX`, `LINX`, `Frankfurt`
    """
    cache_key = cache_module.make_ixp_key(query)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.lookup_ixps(query)
    md  = format_ixp_lookup_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_IXP)
    return _resp(md, jsn, format)


@app.get(
    "/v1/health/{resource}",
    tags=["Health"],
    summary="One-shot health check: RDAP + BGP + RPKI + PeeringDB",
)
async def network_health(
    resource: str,
    format: str = FORMAT_QUERY,
):
    """
    Comprehensive parallel health check: fires RDAP + BGP + RPKI + PeeringDB
    simultaneously and returns a unified health signal dashboard.

    🚨 Critical: RPKI invalid, multiple origin ASNs (possible hijack)
    ⚠️  Warning: not announced, no ROA, missing abuse contact
    ✅ Healthy: registered, announced, RPKI valid

    **Examples:** `1.1.1.1`, `1.1.1.0/24`, `AS13335`
    """
    cache_key = cache_module.make_health_key(resource)
    cached = cache_module.get(cache_key)
    if cached:
        return _resp(cached["markdown"], cached["json"], format)

    result = await rir_client.get_network_health(resource)
    md  = format_network_health_md(result)
    jsn = to_json(result)
    cache_module.set(cache_key, {"markdown": md, "json": jsn}, cache_module.TTL_HEALTH)
    return _resp(md, jsn, format)


@app.get(
    "/v1/monitor/{resource}",
    tags=["Monitor"],
    summary="Monitor registration + BGP changes between calls",
)
async def change_monitor(
    resource: str,
    reset: bool = Query(
        default=False,
        description="Set to true to discard the stored baseline and start fresh",
    ),
):
    """
    Stateful change monitor for a prefix or ASN.

    - **First call:** captures a baseline snapshot (RDAP + BGP state).
    - **Later calls:** diffs current state vs baseline and reports changes.
    - **reset=true:** discards baseline, captures fresh snapshot.

    Tracked: holder, RIR, country, allocation status, abuse email,
    BGP announced, origin ASN(s), BGP visibility %.

    ⚠️ Baselines live in server memory — lost on server restart.

    **Examples:** `8.8.8.0/24`, `AS15169`
    """
    result = await rir_client.run_change_monitor(
        resource=resource,
        reset_baseline=reset,
    )
    md  = format_change_monitor_md(result)
    jsn = to_json(result)
    # Always return JSON for monitor (structured diff is more useful)
    import json
    try:
        return JSONResponse(content=json.loads(jsn))
    except Exception:
        return PlainTextResponse(content=md)


# ──────────────────────────────────────────────────────────────
# OpenAI / Gemini function-calling schema endpoint
# ──────────────────────────────────────────────────────────────

@app.get(
    "/v1/meta/openai-tools",
    tags=["Meta"],
    summary="OpenAI / Gemini function-calling tool definitions",
)
async def openai_tools():
    """
    Returns the tool definitions in OpenAI function-calling format.
    Paste these directly into your ChatGPT/Gemini system prompt or
    API call to give those models access to PeerGlass.
    """
    tools = [
        {
            "type": "function",
            "function": {
                "name": "peerglass_ip",
                "description": "Who owns this IP address? Queries all 5 RIRs (RDAP).",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "ip": {"type": "string", "description": "IPv4 or IPv6 address"}
                    },
                    "required": ["ip"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "peerglass_asn",
                "description": "Who owns this Autonomous System Number (ASN)?",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "asn": {"type": "string", "description": "ASN, e.g. 'AS13335' or '13335'"}
                    },
                    "required": ["asn"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "peerglass_health",
                "description": (
                    "One-shot network health check combining RDAP registration, "
                    "BGP routing status, RPKI validity, and PeeringDB peering policy. "
                    "Best first tool for any IP/prefix/ASN investigation."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "resource": {
                            "type": "string",
                            "description": "IP address, prefix (CIDR), or ASN",
                        }
                    },
                    "required": ["resource"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "peerglass_rpki",
                "description": "Is this BGP route RPKI valid? Returns valid/invalid/not-found.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "prefix": {"type": "string", "description": "IP prefix in CIDR, e.g. '1.1.1.0/24'"},
                        "asn": {"type": "string", "description": "Origin ASN, e.g. 'AS13335'"},
                    },
                    "required": ["prefix", "asn"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "peerglass_peering",
                "description": "PeeringDB lookup: peering policy, IXP presence, NOC contacts for an ASN.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "asn": {"type": "string", "description": "ASN, e.g. 'AS13335'"}
                    },
                    "required": ["asn"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "peerglass_ixp",
                "description": "Find Internet Exchange Points by country code (e.g. 'MU') or name (e.g. 'AMS-IX').",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string", "description": "Country code or IXP name fragment"}
                    },
                    "required": ["query"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "peerglass_history",
                "description": "Full ownership and status history for a prefix or ASN.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "resource": {"type": "string", "description": "IP prefix or ASN"}
                    },
                    "required": ["resource"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "peerglass_monitor",
                "description": (
                    "Monitor a prefix or ASN for changes between calls. "
                    "First call captures baseline; subsequent calls return a diff."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "resource": {"type": "string", "description": "IP prefix or ASN"},
                        "reset": {"type": "boolean", "description": "Reset baseline (default false)"},
                    },
                    "required": ["resource"],
                },
            },
        },
    ]
    return {"tools": tools, "count": len(tools), "base_url": "https://api.peerglass.io"}
